name: Action for Building, Merging and Uploading Binaries to Github Pages - ESP Launchpad
description: 'Builds and uploads binaries to github pages for ESP Launchpad'

inputs:
  github_token:
    description: 'GitHub token'
    required: true
  idf_version:
    description: 'IDF version'
    required: false
    default: 'latest'
  parallel_count:
    description: 'Number of parallel builds'
    required: false
    default: 1
  parallel_index:
    description: 'Index of the current parallel build'
    required: false
    default: 1

runs:
  using: 'composite'
  steps:
    - name: Get Env variables
      shell: bash
      run: echo "IDF_VERSION=${{ inputs.idf_version }}" >> $GITHUB_ENV

    - name: Fetch generateFiles.py
      shell: bash 
      run: |
        curl \
          -H "Accept: application/vnd.github.v3.raw" \
          -o generateFiles.py \
          -L https://api.github.com/repos/XDanielPaul/idf-examples-launchpad-ci-action/contents/generateFiles.py?ref=v1.0

    - name: Build examples
      shell: bash
      run: |
        export IDF_EXTRA_ACTIONS_PATH=${GITHUB_WORKSPACE}/examples
        ${IDF_PATH}/install.sh --enable-ci
        . ${IDF_PATH}/export.sh
        pip install rtoml ruamel.yaml --upgrade
        echo "Building examples..."
        idf-build-apps build --collect-app-info out.json --build-dir "build_@w" --parallel-count ${{ inputs.parallel_count }} --parallel-index ${{ inputs.parallel_index }}
        echo "Merging binaries and creating config.toml..."
        python generateFiles.py out.json
        echo "Uploading binaries..."

    - name: Upload binaries to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./binaries

branding:
  icon: 'package'
  color: 'blue'